&lt;h1&gt;Login&lt;/h1&gt;
&lt;form&gt;
  &lt;label for="username"&gt;Username:&lt;/label&gt;
  &lt;input type="text" id="username" name="username"&gt;
  &lt;br&gt;
  &lt;label for="password"&gt;Password:&lt;/label&gt;
  &lt;input type="password" id="password" name="password"&gt;
  &lt;br&gt;
  &lt;button type="submit"&gt;Login&lt;/button&gt;
&lt;/form&gt;